"""Typing protocols for Scholar MCP services."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from ._record_types import (
    BookRecord,  # noqa: TC001 — runtime import needed for get_type_hints()
    StandardRecord,  # noqa: TC001 — runtime import needed for get_type_hints()
)


@runtime_checkable
class CacheProtocol(Protocol):
    """Structural type for the scholar cache.

    Covers paper, patent, and book cache methods. Using a protocol
    allows ``mypy`` to catch missing or misnamed methods at type-check
    time rather than at runtime.
    """

    # Paper methods
    async def get_paper(self, paper_id: str) -> dict[str, Any] | None: ...
    async def set_paper(self, paper_id: str, data: dict[str, Any]) -> None: ...
    async def get_citations(self, paper_id: str) -> list[str] | None: ...
    async def set_citations(self, paper_id: str, ids: list[str]) -> None: ...
    async def get_references(self, paper_id: str) -> list[str] | None: ...
    async def set_references(self, paper_id: str, ids: list[str]) -> None: ...
    async def get_author(self, author_id: str) -> dict[str, Any] | None: ...
    async def set_author(self, author_id: str, data: dict[str, Any]) -> None: ...
    async def get_openalex(self, doi: str) -> dict[str, Any] | None: ...
    async def set_openalex(self, doi: str, data: dict[str, Any]) -> None: ...
    async def get_alias(self, raw_id: str) -> str | None: ...
    async def set_alias(self, raw_id: str, s2_paper_id: str) -> None: ...

    # Patent methods
    async def get_patent(self, patent_id: str) -> dict[str, Any] | None: ...
    async def set_patent(self, patent_id: str, data: dict[str, Any]) -> None: ...
    async def get_patent_claims(self, patent_id: str) -> str | None: ...
    async def set_patent_claims(self, patent_id: str, text: str) -> None: ...
    async def get_patent_description(self, patent_id: str) -> str | None: ...
    async def set_patent_description(self, patent_id: str, text: str) -> None: ...
    async def get_patent_family(
        self, patent_id: str
    ) -> list[dict[str, Any]] | None: ...
    async def set_patent_family(
        self, patent_id: str, data: list[dict[str, Any]]
    ) -> None: ...
    async def get_patent_legal(self, patent_id: str) -> list[dict[str, Any]] | None: ...
    async def set_patent_legal(
        self, patent_id: str, data: list[dict[str, Any]]
    ) -> None: ...
    async def get_patent_citations(self, patent_id: str) -> dict[str, Any] | None: ...
    async def set_patent_citations(
        self, patent_id: str, data: dict[str, Any]
    ) -> None: ...
    async def get_patent_search(self, query: str) -> dict[str, Any] | None: ...
    async def set_patent_search(self, query: str, data: dict[str, Any]) -> None: ...

    # Book methods
    async def get_book_by_isbn(self, isbn: str) -> BookRecord | None: ...
    async def set_book_by_isbn(self, isbn: str, data: BookRecord) -> None: ...
    async def get_book_by_work(self, work_id: str) -> BookRecord | None: ...
    async def set_book_by_work(self, work_id: str, data: BookRecord) -> None: ...
    async def get_book_search(self, query: str) -> list[BookRecord] | None: ...
    async def set_book_search(self, query: str, data: list[BookRecord]) -> None: ...
    async def get_book_subject(self, cache_key: str) -> list[BookRecord] | None: ...
    async def set_book_subject(
        self, cache_key: str, data: list[BookRecord]
    ) -> None: ...

    # CrossRef methods
    async def get_crossref(self, doi: str) -> dict[str, Any] | None: ...
    async def set_crossref(self, doi: str, data: dict[str, Any]) -> None: ...

    # Google Books methods
    async def get_google_books(self, isbn: str) -> dict[str, Any] | None: ...
    async def set_google_books(self, isbn: str, data: dict[str, Any]) -> None: ...

    # Standards methods
    async def get_standard(self, identifier: str) -> StandardRecord | None: ...
    async def set_standard(
        self,
        identifier: str,
        data: StandardRecord,
        *,
        source: str | None = None,
        synced: bool = False,
    ) -> None: ...
    async def get_standard_alias(self, raw: str) -> str | None: ...
    async def set_standard_alias(self, raw: str, canonical: str) -> None: ...
    async def list_synced_standard_ids(self, source: str) -> set[str]: ...
    async def search_synced_standards(
        self,
        query: str,
        *,
        source: str | None = None,
        limit: int = 10,
    ) -> list[StandardRecord]: ...
    async def get_standards_search(self, query: str) -> list[StandardRecord] | None: ...
    async def set_standards_search(
        self, query: str, data: list[StandardRecord]
    ) -> None: ...
    async def get_standards_index(self, body: str) -> list[dict[str, Any]] | None: ...
    async def set_standards_index(
        self, body: str, data: list[dict[str, Any]]
    ) -> None: ...

    # Standards sync-run methods
    async def set_sync_run(
        self,
        *,
        body: str,
        upstream_ref: str | None,
        added: int,
        updated: int,
        unchanged: int,
        withdrawn: int,
        errors: list[str],
        started_at: float,
        finished_at: float,
    ) -> None: ...
    async def get_sync_run(self, body: str) -> dict[str, Any] | None: ...
    async def list_sync_runs(self) -> list[dict[str, Any]]: ...
