#!/usr/bin/env python3
"""Generate the Reference pages from the registered server (#716).

Builds the project's server once and writes ``docs/reference/`` from what it
registers: one page per tool group, the tools jump table, resources,
prompts and the command line.  A fact on these pages changes at its source
(a docstring, an annotation, a CLI option); prose lives only in the
``DOMAIN-INTRO`` and ``DOMAIN-EXAMPLE-<name>`` slots, which survive
regeneration.

A tool's group is its ``group:<slug>`` tag, else the last segment of the
registering module (``pkg._tools.reader`` -> ``reader``), or the package
above it when that segment is ``register`` (``pkg._jobs.register`` ->
``jobs``).  The description a page shows is the wire description FastMCP
sends, so the two cannot disagree; ``Returns:`` and ``Raises:`` come from
the raw docstring, which the wire drops.

The script is template-owned and byte-identical in every project: it reads
``python_module`` and ``project_name`` from ``.copier-answers.yml`` and
imports ``<module>.server.make_server`` and ``<module>.cli.app``.  The server
is built for the ``http`` transport, the widest surface: a component a
project registers for HTTP alone, such as the transfer-link tools, is
documented too (#749).  Variables a project's ``from_env`` requires, and
what its HTTP-only wiring needs at build time (a transfer project's
``<PREFIX>_BASE_URL``), come from ``[tool.docs-reference] env`` in
``pyproject.toml``.

Usage::

    python scripts/gen_reference.py            # write docs/reference/ and the nav region
    python scripts/gen_reference.py --check    # exit 1 when a page or the nav is stale

Run from the project root; it reads and writes the current directory.
"""

from __future__ import annotations

import argparse
import asyncio
import difflib
import inspect
import json
import logging
import os
import re
import sys
import tomllib
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, Any

import yaml

if TYPE_CHECKING:
    from collections.abc import Iterable, Iterator

    import typer
    from fastmcp import FastMCP

MARKER = (
    "<!-- generated by scripts/gen_reference.py; edit the docstrings, not this page -->"
)
GROUP_TAG = "group:"
NAV_START = "GENERATED-NAV-TOOLS-START"
NAV_END = "GENERATED-NAV-TOOLS-END"
SECURITY_MODEL = "../../security-model.md"

# The Google-style headings FastMCP strips from a docstring when it builds
# the wire description; the same set tests/test_model_facing_text.py pins.
_SECTION = re.compile(
    r"^[ \t]*(Args|Arguments|Parameters|Returns|Yields|Raises|Examples?):[ \t]*$",
    re.MULTILINE,
)
_COMMENT_ONLY = re.compile(r"<!--.*?-->", re.DOTALL)
_SLOT = re.compile(
    r"<!-- (DOMAIN-[A-Za-z0-9_.-]+?)-START -->\n(.*?)<!-- \1-END -->", re.DOTALL
)


class GenerationError(Exception):
    """The reference cannot be generated as the code stands."""


class BuildError(GenerationError):
    """The project's server or CLI could not be built (exit 2)."""


@dataclass(frozen=True)
class Param:
    name: str
    type: str
    default: str
    description: str


@dataclass(frozen=True)
class ToolEntry:
    name: str
    title: str
    group: str
    security: list[str]
    tags: list[str]
    description: str
    params: list[Param]
    returns: str
    raises: list[str]
    output_type: str


@dataclass(frozen=True)
class ResourceEntry:
    name: str
    uri: str
    description: str
    mime_type: str
    parameters: list[str]


@dataclass(frozen=True)
class PromptArg:
    name: str
    required: bool
    description: str


@dataclass(frozen=True)
class PromptEntry:
    name: str
    description: str
    arguments: list[PromptArg]


@dataclass(frozen=True)
class CliArgument:
    name: str
    help: str


@dataclass(frozen=True)
class CliOption:
    name: str
    envvar: str
    default: str
    help: str


@dataclass(frozen=True)
class CliCommand:
    name: str
    help: str
    arguments: list[CliArgument]
    options: list[CliOption]


@dataclass(frozen=True)
class Cli:
    name: str
    help: str
    commands: list[CliCommand]


@dataclass
class Reference:
    groups: dict[str, list[ToolEntry]] = field(default_factory=dict)
    resources: list[ResourceEntry] = field(default_factory=list)
    prompts: list[PromptEntry] = field(default_factory=list)
    cli: Cli = field(default_factory=lambda: Cli("", "", []))


# ---------------------------------------------------------------------------
# Collect
# ---------------------------------------------------------------------------


def _sections(doc: str) -> dict[str, str]:
    """Split a Google-style docstring into its named sections."""
    parts = _SECTION.split(doc)
    found: dict[str, str] = {}
    for heading, body in zip(parts[1::2], parts[2::2], strict=True):
        found[heading] = inspect.cleandoc(body).strip()
    return found


def _entries(section: str) -> list[str]:
    """Split a Google-style section into entries; indented lines continue one."""
    entries: list[str] = []
    for line in section.splitlines():
        if not line.strip():
            continue
        if entries and line[:1].isspace():
            entries[-1] = f"{entries[-1]} {line.strip()}"
        else:
            entries.append(line.strip())
    return entries


def _module_group(module: str) -> str:
    """The group a module names: its last segment, or the package above a ``register`` module.

    A module called ``register`` names the act, not the feature: pvl-core
    registers its jobs and transfer-link tools from ``_jobs.register`` and
    ``_transfer.register``, and a project cannot tag a library's tool (#760).
    """
    parts = [part.lstrip("_") for part in module.split(".")]
    if len(parts) > 1 and parts[-1] == "register":
        parts.pop()
    return parts[-1]


def _group_of(tool: Any) -> str:
    groups = sorted(
        t[len(GROUP_TAG) :] for t in tool.tags or () if t.startswith(GROUP_TAG)
    )
    if len(groups) > 1:
        raise GenerationError(
            f"tool {tool.name} carries two group tags: {', '.join(groups)}"
        )
    group = groups[0] if groups else _module_group(tool.fn.__module__)
    if group == "index":
        raise GenerationError(
            f"tool {tool.name}: group 'index' would overwrite the tools jump table; "
            "pick another group: tag"
        )
    return group


def _security(annotations: Any) -> list[str]:
    """The security line, read the way a client reads the annotations.

    The MCP spec's defaults apply where a hint is unset: not read-only, and
    destructive. An unstated hint is therefore rendered as what a client
    assumes, never as something milder.
    """
    if annotations is None:
        return [
            "No annotations: clients assume it changes state and may be destructive."
        ]
    lines = []
    if annotations.read_only_hint:
        lines.append("Read-only.")
    elif annotations.destructive_hint:
        lines.append("Destructive.")
    elif annotations.destructive_hint is False:
        lines.append("Changes state, not destructive.")
    else:
        lines.append("Changes state; may be destructive (no destructive hint given).")
    if annotations.idempotent_hint:
        lines.append("Idempotent.")
    if annotations.open_world_hint:
        lines.append("Reaches outside the server.")
    return lines


def _visibility(meta: Any) -> list[str]:
    """The MCP Apps visibility hint (``meta.ui.visibility``), when set."""
    ui = meta.get("ui") if isinstance(meta, dict) else None
    visible = ui.get("visibility") if isinstance(ui, dict) else None
    if not visible:
        return []
    return [f"Visible to: {', '.join(str(v) for v in visible)}."]


def _schema_type(prop: dict[str, Any]) -> str:
    if "enum" in prop:
        return " | ".join(str(v) for v in prop["enum"])
    if "anyOf" in prop:
        return " | ".join(_schema_type(p) for p in prop["anyOf"])
    if "$ref" in prop:
        return str(prop["$ref"]).rsplit("/", 1)[-1]
    kind = prop.get("type", "any")
    if kind == "array" and "items" in prop:
        return f"array of {_schema_type(prop['items'])}"
    return str(kind)


def _params(schema: dict[str, Any]) -> list[Param]:
    required = set(schema.get("required") or ())
    defs = schema.get("$defs") or {}
    out = []
    for name, prop in (schema.get("properties") or {}).items():
        resolved = defs.get(str(prop.get("$ref", "")).rsplit("/", 1)[-1], prop)
        if name in required:
            default = "required"
        elif "default" in prop:
            default = json.dumps(prop["default"])
        else:
            default = "optional"
        out.append(
            Param(
                name,
                _schema_type(resolved),
                default,
                str(prop.get("description") or ""),
            )
        )
    return out


def _output_type(schema: dict[str, Any] | None) -> str:
    if not schema:
        return ""
    if schema.get("x-fastmcp-wrap-result"):
        return _schema_type(schema["properties"]["result"])
    return _schema_type(schema)


def _tool_entry(tool: Any) -> ToolEntry:
    sections = _sections(inspect.getdoc(tool.fn) or "")
    raises = _entries(sections.get("Raises", ""))
    tags = sorted(t for t in tool.tags or () if not t.startswith(GROUP_TAG))
    return ToolEntry(
        name=tool.name,
        title=(tool.annotations.title if tool.annotations else None)
        or tool.title
        or tool.name,
        group=_group_of(tool),
        security=_security(tool.annotations) + _visibility(tool.meta),
        tags=tags,
        description=(tool.description or "").strip(),
        params=_params(tool.parameters or {}),
        returns=sections.get("Returns", ""),
        raises=raises,
        output_type=_output_type(tool.output_schema),
    )


def _cli_command(name: str, cmd: Any) -> CliCommand:
    """One click command as arguments and visible options."""
    arguments, options = [], []
    for param in cmd.params:
        help_text = getattr(param, "help", "") or ""
        if param.param_type_name == "argument":
            arguments.append(CliArgument(str(param.name).upper(), help_text))
        elif param.param_type_name == "option" and not getattr(param, "hidden", False):
            default = "" if param.default is None else str(param.default)
            envvar = param.envvar if isinstance(param.envvar, str) else ""
            options.append(CliOption(param.opts[0], envvar, default, help_text))
    return CliCommand(name, cmd.help or "", arguments, options)


def _cli(app: typer.Typer, name: str) -> Cli:
    import typer.main

    # typer vendors its own click, so duck-type the objects instead of
    # isinstance checks against the click package.
    root = typer.main.get_command(app)
    members = getattr(root, "commands", None)
    pairs = members.items() if members is not None else [(root.name, root)]
    commands = [
        _cli_command(str(cmd_name), cmd)
        for cmd_name, cmd in pairs
        if not getattr(cmd, "hidden", False)
    ]
    return Cli(name, root.help or "", commands)


def collect(server: FastMCP, app: typer.Typer, command_name: str) -> Reference:
    """Read every registered component of *server* and *app*."""

    async def _list() -> tuple[Any, Any, Any, Any]:
        return (
            await server.list_tools(),
            await server.list_resources(),
            await server.list_resource_templates(),
            await server.list_prompts(),
        )

    tools, resources, templates, prompts = asyncio.run(_list())
    ref = Reference()
    for tool in tools:
        entry = _tool_entry(tool)
        ref.groups.setdefault(entry.group, []).append(entry)
    for res in resources:
        ref.resources.append(
            ResourceEntry(
                res.name, str(res.uri), res.description or "", res.mime_type or "", []
            )
        )
    for tpl in templates:
        params = list((tpl.parameters or {}).get("properties") or {})
        ref.resources.append(
            ResourceEntry(
                tpl.name,
                tpl.uri_template,
                tpl.description or "",
                tpl.mime_type or "",
                params,
            )
        )
    for prompt in prompts:
        ref.prompts.append(
            PromptEntry(
                prompt.name,
                prompt.description or "",
                [
                    PromptArg(a.name, bool(a.required), a.description or "")
                    for a in prompt.arguments or ()
                ],
            )
        )
    ref.cli = _cli(app, command_name)
    return ref


# ---------------------------------------------------------------------------
# Render
# ---------------------------------------------------------------------------


def _first_sentence(text: str) -> str:
    guard = r"(?<!\be\.g\.)(?<!\bi\.e\.)(?<!\betc\.)(?<!\bvs\.)(?<!\bapprox\.)"
    return re.split(guard + r"(?<=[.!?])\s", text.strip(), maxsplit=1)[0]


def _title(slug: str) -> str:
    text = slug.replace("-", " ").replace("_", " ")
    return text[:1].upper() + text[1:]


def _slot(name: str, body: str, placeholder: str) -> str:
    content = body if body.strip() else placeholder + "\n"
    return f"<!-- {name}-START -->\n{content}<!-- {name}-END -->\n"


def _front(description: str) -> str:
    return f"---\ndescription: {json.dumps(description)}\nkind: reference\n---\n\n{MARKER}\n\n"


def _existing_slots(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    return dict(_SLOT.findall(path.read_text(encoding="utf-8-sig")))


def _table(header: Iterable[str], rows: Iterable[Iterable[str]]) -> str:
    head = list(header)
    lines = ["| " + " | ".join(head) + " |", "|" + "---|" * len(head)]
    lines.extend("| " + " | ".join(_cell(c) for c in row) + " |" for row in rows)
    return "\n".join(lines) + "\n"


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


# Stretches _prose never touches: code spans and Markdown links.  A code span
# is CommonMark's: a run of backticks closed by the next run of the same
# length, so an RST-style ``double`` span is one span, not two empty ones (#747).
_OPENER = re.compile(r"[`\[]")
_RUN = re.compile(r"`+")
# Link text holds no bracket and the target no parenthesis, so a failed match
# stops at the next opener and the scan stays linear.
_LINK = re.compile(r"\[[^\[\]]*\]\([^()]*\)")
# Not next to a backtick: an unclosed run is literal text, and wrapping the
# word beside it would lengthen the run into a different one.
_IDENTIFIER = re.compile(r"(?<!`)\b[A-Za-z0-9]+(?:_[A-Za-z0-9]+)+\b(?!`)")


def _literals(text: str) -> Iterator[tuple[int, int]]:
    """Yield ``(start, end)`` of each code span and link, left to right.

    Whichever starts first wins, as in CommonMark.  A backtick run with no
    closing run of its length is literal text.  Linear in ``len(text)``:
    every run's closer is looked up, not searched for.
    """
    runs = [(m.start(), m.end()) for m in _RUN.finditer(text)]
    closer: dict[int, int] = {}  # run start -> end of the next run as long
    later: dict[int, int] = {}  # run length -> end of the nearest later run
    for start, end in reversed(runs):
        if end - start in later:
            closer[start] = later[end - start]
        later[end - start] = end
    run_end = dict(runs)
    position = 0
    while opener := _OPENER.search(text, position):
        start = opener.start()
        if text[start] == "[":
            link = _LINK.match(text, start)
            position = link.end() if link else start + 1
            if link:
                yield start, link.end()
        elif start in closer:
            position = closer[start]
            yield start, position
        else:
            position = run_end.get(start, start + 1)


def _prose(text: str) -> str:
    """Format snake_case identifiers in docstring prose as code.

    The words stay the wire's words; only the formatting changes, so Vale
    spell-checks prose and leaves identifiers alone. Existing code spans and
    links are left as they are.
    """
    out = []
    position = 0
    for start, end in _literals(text):
        out.append(_code_identifiers(text[position:start]))
        out.append(text[start:end])
        position = end
    out.append(_code_identifiers(text[position:]))
    return "".join(out)


def _code_identifiers(prose: str) -> str:
    return _IDENTIFIER.sub(lambda m: f"`{m.group(0)}`", prose)


def _default_cell(default: str) -> str:
    return default if default in ("required", "optional") else f"`{default}`"


def _tool_section(tool: ToolEntry, slots: dict[str, str], used: set[str]) -> str:
    out = [f"## `{tool.name}`\n\n"]
    if tool.title != tool.name:
        out.append(f"**{tool.title}.** ")
    out.append(" ".join(tool.security))
    if tool.tags:
        out.append(f" Tags: {', '.join(f'`{t}`' for t in tool.tags)}.")
    out.append("\n\n")
    if tool.description:
        out.append(_prose(tool.description) + "\n\n")
    out.append("**Parameters**\n\n")
    if tool.params:
        out.append(
            _table(
                ("Name", "Type", "Default", "Description"),
                (
                    (
                        f"`{p.name}`",
                        f"`{p.type}`",
                        _default_cell(p.default),
                        _prose(p.description),
                    )
                    for p in tool.params
                ),
            )
        )
    else:
        out.append("None.\n")
    out.append("\n**Returns**\n\n")
    out.append(
        (
            _prose(tool.returns)
            or (f"`{tool.output_type}`" if tool.output_type else "Nothing.")
        )
        + "\n\n"
    )
    if tool.raises:
        out.append("**Outcomes and errors**\n\n")
        out.extend(f"- {_prose(line)}\n" for line in tool.raises)
        out.append("\n")
    slot = f"DOMAIN-EXAMPLE-{tool.name}"
    used.add(slot)
    out.append(
        _slot(
            slot,
            slots.get(slot, ""),
            "<!-- A worked example for this tool; kept across regeneration. -->",
        )
    )
    out.append("\n")
    return "".join(out)


def _page(
    path: Path, description: str, heading: str, body_fn: Any, preface: str = ""
) -> str:
    """Assemble a page: front matter, heading, the intro slot, *preface*, body.

    *preface* is template-owned prose that every regeneration rewrites (unlike
    the slots), used for the client guidance on the prompts and resources pages.
    The shipped seed pages under ``docs/reference/`` carry the same text, so a
    fresh render passes ``--check``; change the constant and the seed together.
    """
    slots = _existing_slots(path)
    used = {"DOMAIN-INTRO"}
    body = body_fn(slots, used)
    orphans = sorted(set(slots) - used)
    if orphans:
        raise GenerationError(
            f"{path}: slot {', '.join(orphans)} matches no registered component; "
            "move its content or delete the slot"
        )
    intro = _slot(
        "DOMAIN-INTRO",
        slots.get("DOMAIN-INTRO", ""),
        "<!-- A short orientation for this page; task guidance belongs under Use. Kept across regeneration. -->",
    )
    return _front(description) + f"# {heading}\n\n" + intro + "\n" + preface + body


def _group_page(group: str, tools: list[ToolEntry], path: Path) -> str:
    def body(slots: dict[str, str], used: set[str]) -> str:
        return "".join(_tool_section(t, slots, used) for t in tools).rstrip("\n") + "\n"

    return _page(
        path, f"Reference for the {_title(group)} group of tools.", _title(group), body
    )


def _index_page(ref: Reference, path: Path) -> str:
    def body(_slots: dict[str, str], _used: set[str]) -> str:
        rows = [
            (
                _title(group),
                f"[`{t.name}`]({group}.md#{t.name})",
                _prose(t.title),
                _prose(_first_sentence(t.description)),
            )
            for group, tools in ref.groups.items()
            for t in tools
        ]
        text = (
            "Every tool runs with the server's own privileges; the "
            f"[security model]({SECURITY_MODEL}) says what that reaches.\n\n"
        )
        return text + _table(("Group", "Tool", "Title", "Does"), rows)

    return _page(path, "Every tool this server registers, by group.", "Tools", body)


_PROMPTS_PREFACE = """## Running a prompt

A prompt is a template this server fills from the arguments listed with it and hands to your client as a message, so a task starts with the server's own instructions. It runs the same tools with the same access as anything you type. How to start one depends on the client:

- **Claude Code** lists each prompt in the `/` menu as `/<server>:<prompt> (MCP)`, where `<server>` is the name you gave this server when you added it. Typing `/mcp__<server>__<prompt>` runs it too; arguments follow it separated by spaces, each a single token.
- **claude.ai and Claude Desktop** offer a connector's prompts from the compose area's **+** menu once the connector is added.

"""

_RESOURCES_PREFACE = """## Reading a resource

A resource is data this server serves at a URI, for a client to attach to the conversation rather than for the model to call. In Claude Code, mention one as `@<server>:<uri>`, where `<server>` is the name you gave this server when you added it; a resource template takes its parameters in the URI.

"""


def _resources_page(ref: Reference, path: Path) -> str:
    def body(_slots: dict[str, str], _used: set[str]) -> str:
        if not ref.resources:
            return "This server registers no resources.\n"
        out = []
        for r in ref.resources:
            out.append(f"## `{r.name}`\n\n`{r.uri}`")
            if r.mime_type:
                out.append(f" ({r.mime_type})")
            out.append("\n\n")
            if r.description:
                out.append(_prose(r.description) + "\n\n")
            if r.parameters:
                out.append(
                    "Parameters: " + ", ".join(f"`{p}`" for p in r.parameters) + ".\n\n"
                )
        return "".join(out).rstrip("\n") + "\n"

    return _page(
        path,
        "The resources and resource templates this server serves.",
        "Resources",
        body,
        preface=_RESOURCES_PREFACE,
    )


def _prompts_page(ref: Reference, path: Path) -> str:
    def body(slots: dict[str, str], used: set[str]) -> str:
        if not ref.prompts:
            return "This server registers no prompts.\n"
        out = []
        for p in ref.prompts:
            out.append(f"## `{p.name}`\n\n")
            if p.description:
                out.append(_prose(p.description) + "\n\n")
            if p.arguments:
                out.append(
                    _table(
                        ("Argument", "Required", "Description"),
                        (
                            (
                                f"`{a.name}`",
                                "yes" if a.required else "no",
                                _prose(a.description),
                            )
                            for a in p.arguments
                        ),
                    )
                    + "\n"
                )
            slot = f"DOMAIN-EXAMPLE-{p.name}"
            used.add(slot)
            out.append(
                _slot(
                    slot,
                    slots.get(slot, ""),
                    "<!-- A worked example for this prompt; kept across regeneration. -->",
                )
            )
            out.append("\n")
        return "".join(out).rstrip("\n") + "\n"

    return _page(
        path,
        "The prompt templates this server offers to MCP clients.",
        "Prompts",
        body,
        preface=_PROMPTS_PREFACE,
    )


def _command_section(cli_name: str, c: CliCommand) -> str:
    out = [f"## `{cli_name} {c.name}`\n\n"]
    if c.help:
        out.append(_prose(c.help) + "\n\n")
    if c.arguments:
        argument_rows = ((f"`{a.name}`", _prose(a.help)) for a in c.arguments)
        out.append(_table(("Argument", "Description"), argument_rows) + "\n")
    if c.options:
        rows = (
            (
                f"`{o.name}`",
                f"`{o.envvar}`" if o.envvar else "",
                o.default,
                _prose(o.help),
            )
            for o in c.options
        )
        out.append(_table(("Option", "Env var", "Default", "Description"), rows) + "\n")
    return "".join(out)


def _cli_page(ref: Reference, path: Path) -> str:
    def body(_slots: dict[str, str], _used: set[str]) -> str:
        intro = _prose(ref.cli.help) + "\n\n" if ref.cli.help else ""
        sections = "".join(_command_section(ref.cli.name, c) for c in ref.cli.commands)
        return (intro + sections).rstrip("\n") + "\n"

    return _page(
        path,
        f"The `{ref.cli.name}` command line: commands, options and their environment variables.",
        "Command line",
        body,
    )


def render(ref: Reference, docs: Path) -> dict[str, str]:
    """Return every generated page, path relative to *docs* -> text."""
    pages: dict[str, str] = {}
    for group, tools in ref.groups.items():
        rel = f"reference/tools/{group}.md"
        pages[rel] = _group_page(group, tools, docs / rel)
    for rel, fn in (
        ("reference/tools/index.md", _index_page),
        ("reference/resources.md", _resources_page),
        ("reference/prompts.md", _prompts_page),
        ("reference/cli.md", _cli_page),
    ):
        pages[rel] = fn(ref, docs / rel)
    # After every page is in: the jump table sits beside the group pages and
    # would otherwise count as a vanished group (#761).
    _guard_stale(docs, pages)
    return pages


def _stale(docs: Path, pages: dict[str, str]) -> list[Path]:
    """Generated group pages on disk that this run did not produce."""
    tools = docs / "reference" / "tools"
    if not tools.is_dir():
        return []
    return sorted(
        p
        for p in tools.glob("*.md")
        if f"reference/tools/{p.name}" not in pages
        and MARKER in p.read_text(encoding="utf-8-sig")
    )


def _guard_stale(docs: Path, pages: dict[str, str]) -> None:
    """Refuse to continue while a vanished group's page still holds prose."""
    for stale in _stale(docs, pages):
        written = [
            name
            for name, body in _existing_slots(stale).items()
            if _COMMENT_ONLY.sub("", body).strip()
        ]
        if written:
            raise GenerationError(
                f"{stale}: no tool group writes this page any more, but its slot(s) "
                f"{', '.join(written)} hold content; move it to the new group page, "
                "then delete the file"
            )


def check(docs: Path, pages: dict[str, str]) -> list[str]:
    """Return diff lines for every page that differs from disk, and stale files."""
    lines: list[str] = []
    for rel, text in sorted(pages.items()):
        path = docs / rel
        current = path.read_text(encoding="utf-8-sig") if path.exists() else ""
        if current != text:
            lines.extend(
                difflib.unified_diff(
                    current.splitlines(),
                    text.splitlines(),
                    f"docs/{rel}",
                    "generated",
                    lineterm="",
                )
            )
    lines.extend(f"stale: {p} (no longer generated)" for p in _stale(docs, pages))
    return lines


def write(docs: Path, pages: dict[str, str]) -> None:
    """Write every page and delete stale generated ones."""
    for stale in _stale(docs, pages):
        stale.unlink()
    for rel, text in pages.items():
        path = docs / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8", newline="\n")


def update_nav(mkdocs_text: str, ref: Reference) -> str:
    """Rewrite the GENERATED-NAV-TOOLS region with one entry per group."""
    lines = mkdocs_text.splitlines(keepends=True)
    starts = [i for i, line in enumerate(lines) if NAV_START in line]
    ends = [i for i, line in enumerate(lines) if NAV_END in line]
    if len(starts) != 1 or len(ends) != 1 or ends[0] < starts[0]:
        raise GenerationError(f"mkdocs.yml: expected one {NAV_START}/{NAV_END} region")
    indent = lines[starts[0]][: len(lines[starts[0]]) - len(lines[starts[0]].lstrip())]
    entries = [f"{indent}- {_title(g)}: reference/tools/{g}.md\n" for g in ref.groups]
    return "".join(lines[: starts[0] + 1] + entries + lines[ends[0] :])


# ---------------------------------------------------------------------------
# Project discovery and entry point
# ---------------------------------------------------------------------------


def _project(root: Path) -> tuple[str, str]:
    """Return ``(python_module, project_name)`` for the project at *root*.

    ``.copier-answers.yml`` is the source while the project tracks the
    template; a detached project has deleted it, so ``[project.scripts]`` in
    ``pyproject.toml`` (``name = "module.cli:main"``) is the fallback.
    """
    answers = root / ".copier-answers.yml"
    if answers.exists():
        data = yaml.safe_load(answers.read_text(encoding="utf-8")) or {}
        if data.get("python_module") and data.get("project_name"):
            return str(data["python_module"]), str(data["project_name"])
    try:
        pyproject = tomllib.loads((root / "pyproject.toml").read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError) as exc:
        raise BuildError(f"cannot read {root / 'pyproject.toml'}: {exc}") from exc
    scripts = pyproject.get("project", {}).get("scripts", {})
    for name, target in scripts.items():
        module = str(target).split(":", 1)[0].rsplit(".", 1)[0]
        if module:
            return module, str(name)
    raise BuildError(
        f"{root}: neither .copier-answers.yml nor [project.scripts] names the package"
    )


def _preset_env(root: Path) -> None:
    try:
        data = tomllib.loads((root / "pyproject.toml").read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError):
        return
    env = data.get("tool", {}).get("docs-reference", {}).get("env", {})
    for key, value in env.items():
        os.environ.setdefault(str(key), str(value))


def _build(root: Path) -> Reference:
    import importlib

    module, project_name = _project(root)
    _preset_env(root)
    sys.path.insert(0, str(root / "src"))
    try:
        server_mod = importlib.import_module(f"{module}.server")
        cli_mod = importlib.import_module(f"{module}.cli")
    except ImportError as exc:
        raise BuildError(f"cannot import {module}: {exc}") from exc
    # The server's own startup and request logs are noise here; errors still show.
    logging.disable(logging.WARNING)
    try:
        server = server_mod.make_server(transport="http")
    except Exception as exc:
        raise BuildError(
            f'make_server(transport="http") failed: {exc}. A required variable '
            "goes under [tool.docs-reference] env in pyproject.toml."
        ) from exc
    try:
        return collect(server, cli_mod.app, project_name)
    except AttributeError as exc:  # a tool without .fn (proxied or transformed)
        raise BuildError(f"cannot read a registered component: {exc}") from exc


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate docs/reference/ from the server; run at the project root."
    )
    parser.add_argument(
        "--check", action="store_true", help="report drift; write nothing"
    )
    args = parser.parse_args(argv)
    root = Path.cwd()
    docs = root / "docs"
    mkdocs = root / "mkdocs.yml"
    try:
        ref = _build(root)
        pages = render(ref, docs)
        nav = update_nav(mkdocs.read_text(encoding="utf-8"), ref)
    except OSError as exc:
        print(f"gen_reference: {exc}", file=sys.stderr)
        return 2
    except BuildError as exc:
        print(f"gen_reference: {exc}", file=sys.stderr)
        return 2
    except GenerationError as exc:
        print(f"gen_reference: {exc}", file=sys.stderr)
        return 1
    drift = check(docs, pages)
    if nav != mkdocs.read_text(encoding="utf-8"):
        drift.append("mkdocs.yml: the GENERATED-NAV-TOOLS region is stale")
    if args.check:
        for line in drift:
            print(line)
        print(f"gen_reference: {'stale' if drift else 'up to date'}")
        return 1 if drift else 0
    write(docs, pages)
    mkdocs.write_text(nav, encoding="utf-8", newline="\n")
    print(f"gen_reference: wrote {len(pages)} page(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
