#!/usr/bin/env python3
"""Report what the template changed in seeded-once files during ``copier update``.

Files under ``_skip_if_exists`` are written on the first ``copier copy`` and
never touched again by ``copier update``, so a template change to one of
them is invisible in the update's diff.  This script runs as the last
after-stage ``_migrations`` entry: it renders the previous and the target
template refs with this project's own answers, diffs every seeded path
between the two, and writes ``.copier-seeded-changes.md`` at the repository
root for the human or agent working the update.  The weekly update pull
request embeds that file.

It never fails the update.  A fresh copy, an unchanged ref, a missing tool
or an impossible render (offline, unknown ref) each leave a clear message —
in the report where one can be written — and exit 0.  Importing this module
has no side effects; the ``uv run`` fallback for missing dependencies runs
from ``main()`` only.
"""

from __future__ import annotations

import difflib
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

REPORT = Path(".copier-seeded-changes.md")
ANSWERS = Path(".copier-answers.yml")

# Skip-listed only for copier's patch mechanics; regenerated in full by
# `scripts/gen_config_surface.py` at the end of every update, so a diff here
# would describe a file the update already rewrote.  `packaging/mcpb/
# manifest.json.in` is deliberately NOT here: the generator rewrites only its
# `user_config` and `server.mcp_config.env` objects, the rest is seeded,
# hand-editable content the template does change, so it stays in the report
# (its regenerated keys may show as noise; the seeded parts are the point).
GENERATED = (
    ".env.example",
    "packaging/env.example",
    "examples/*.env",
    "docs/javascripts/config-wizard/wizard-spec.json",
)

_FENCE = "````"  # four backticks: a seeded markdown file may itself contain ```

_HEADER = """# Seeded files the template changed

<!-- Generated by scripts/report_seeded_changes.py on every `copier update`;
     do not edit.  Files under `_skip_if_exists` are seeded once and never
     re-rendered, so this is the only place their template changes show up. -->

Template `{src}`: `{old}` → `{new}`.
"""


def _read_simple_answers(text: str) -> dict[str, object]:
    """Parse the answers file; PyYAML when importable, else the two keys the
    skip path needs (`_commit`, `_src_path`) from plain `key: value` lines."""
    try:
        import yaml
    except ImportError:
        out: dict[str, object] = {}
        for line in text.splitlines():
            m = re.match(r"^(_commit|_src_path):\s*(.+?)\s*$", line)
            if m:
                out[m.group(1)] = m.group(2).strip("'\"")
        return out
    data = yaml.safe_load(text) or {}
    return data if isinstance(data, dict) else {}


def _git_show_head(path: Path) -> str | None:
    """`HEAD:./path` is relative to the cwd, so a project in a subdirectory works."""
    proc = subprocess.run(
        ["git", "show", f"HEAD:./{path.as_posix()}"],
        capture_output=True,
        text=True,
        check=False,
    )
    return proc.stdout if proc.returncode == 0 else None


def _render_pattern(pattern: str, answers: dict[str, object]) -> str:
    """Render a `_skip_if_exists` pattern such as `src/{{python_module}}/x.py`."""
    return re.sub(
        r"\{\{\s*(\w+)\s*\}\}",
        lambda m: str(answers.get(m.group(1), m.group(0))),
        pattern,
    )


def _skip_patterns(src: str, ref: str) -> list[str]:
    """The template's `_skip_if_exists` at *ref*, via copier's template loader.

    The loader clones the template; clean the clone up ourselves, since only
    a Worker context would otherwise do it."""
    from copier._template import Template  # internal, but the only loader there is

    template = Template(url=src, ref=ref)
    try:
        return list(template.skip_if_exists)
    finally:
        template._cleanup()


def _render(src: str, ref: str, answers: dict[str, object], dst: Path) -> None:
    from copier import run_copy

    data = {k: v for k, v in answers.items() if not k.startswith("_")}
    run_copy(
        src,
        dst,
        data=data,
        vcs_ref=ref,
        defaults=True,
        overwrite=True,
        quiet=True,
        unsafe=True,
        skip_tasks=True,
    )


def matching_files(root: Path, patterns: list[str]) -> set[str]:
    """Files under *root* matching the patterns with copier's gitignore-style
    semantics (`pathspec`, a copier dependency) — `Path.glob` drops files
    under a trailing `**` on Python 3.11 and 3.12."""
    from pathspec import PathSpec

    spec = PathSpec.from_lines("gitignore", patterns)
    return {
        p.relative_to(root).as_posix()
        for p in root.rglob("*")
        if p.is_file() and spec.match_file(p.relative_to(root).as_posix())
    }


def _generated(rel: str) -> bool:
    from pathspec import PathSpec

    return PathSpec.from_lines("gitignore", GENERATED).match_file(rel)


def _lines(path: Path) -> list[str] | None:
    if not path.exists():
        return []
    try:
        return path.read_text(encoding="utf-8").splitlines()
    except UnicodeDecodeError:
        return None


def diff_seeded(
    old_root: Path, new_root: Path, patterns: list[str]
) -> list[tuple[str, str]]:
    """(path, unified diff) for every seeded path that differs between the renders."""
    paths = sorted(
        matching_files(old_root, patterns) | matching_files(new_root, patterns)
    )
    out: list[tuple[str, str]] = []
    for rel in paths:
        if _generated(rel):
            continue
        old_p, new_p = old_root / rel, new_root / rel
        old, new = _lines(old_p), _lines(new_p)
        if old is None or new is None:
            if (
                old_p.exists()
                and new_p.exists()
                and old_p.read_bytes() == new_p.read_bytes()
            ):
                continue
            out.append(
                (rel, "(binary file differs; compare the template refs directly)")
            )
            continue
        if old == new:
            continue
        # Trailing whitespace is stripped from every line (blank context lines
        # come out as a lone space) so the committed report stays clean under
        # the shipped trailing-whitespace hook.
        diff = "\n".join(
            line.rstrip()
            for line in difflib.unified_diff(
                old,
                new,
                fromfile=f"previous/{rel}",
                tofile=f"target/{rel}",
                n=3,
                lineterm="",
            )
        )
        out.append((rel, diff))
    return out


def render_report(
    *, src: str, old: str, new: str, changes: list[tuple[str, str]], failure: str | None
) -> str:
    text = _HEADER.format(src=src, old=old, new=new)
    if failure:
        text += (
            f"\n**The report could not be computed:** {failure}\n\n"
            "Open the template's compare view for the two refs and check every "
            "`_skip_if_exists` path by hand (see `docs/deployment/template-updates.md`).\n"
        )
    elif not changes:
        text += "\nNo seeded file changed between these refs.\n"
    else:
        text += (
            f"\n{len(changes)} seeded file(s) changed. Each is project-owned: apply what "
            "applies, keep your local content, and say in the update pull request what "
            "you did with each.\n"
        )
        for rel, diff in changes:
            text += f"\n## `{rel}`\n\n{_FENCE}diff\n{diff}\n{_FENCE}\n"
    return text.rstrip("\n") + "\n"


def _refs(current: dict[str, object]) -> tuple[str, str, str]:
    """(src, previous ref, target ref); copier's VERSION_FROM/VERSION_TO win
    when it exports them, else the previous ref comes from git HEAD."""
    src = str(current.get("_src_path", ""))
    new = os.environ.get("VERSION_TO") or str(current.get("_commit", ""))
    old = os.environ.get("VERSION_FROM") or ""
    if not old:
        head = _git_show_head(ANSWERS)
        old = str(_read_simple_answers(head).get("_commit", "")) if head else ""
    return src, old, new


def _compute(
    src: str, old: str, new: str, current: dict[str, object]
) -> list[tuple[str, str]]:
    patterns = [_render_pattern(p, current) for p in _skip_patterns(src, new)]
    with tempfile.TemporaryDirectory() as tmp:
        old_root, new_root = Path(tmp) / "previous", Path(tmp) / "target"
        _render(src, old, current, old_root)
        _render(src, new, current, new_root)
        return diff_seeded(old_root, new_root, patterns)


def _skip(reason: str) -> int:
    """A no-op update leaves no stale report behind."""
    if REPORT.exists():
        REPORT.unlink()
        reason += f"; removed the stale {REPORT}"
    print(f"report_seeded_changes: {reason}")
    return 0


def _reexec_with_deps() -> bool:
    """Re-exec under `uv run --no-project` when copier is missing; True when
    the caller should fall through to a failure report instead."""
    try:
        import copier  # noqa: F401
    except ImportError:
        pass
    else:
        return False
    if os.environ.get("_SEEDED_REPORT_BOOTSTRAPPED") == "1":
        return True
    os.environ["_SEEDED_REPORT_BOOTSTRAPPED"] = "1"
    argv = [
        "uv",
        "run",
        "--no-project",
        "--with",
        "copier",
        "python",
        __file__,
        *sys.argv[1:],
    ]
    try:
        os.execvpe("uv", argv, os.environ)
    except OSError:
        return True
    return True  # pragma: no cover — execvpe does not return on success


def main() -> int:
    if not ANSWERS.is_file():
        return _skip("no .copier-answers.yml; nothing to do")
    current = _read_simple_answers(ANSWERS.read_text(encoding="utf-8"))
    src, old, new = _refs(current)
    if not (src and new and old):
        return _skip("no previous template ref (fresh copy?); skipping")
    if old == new:
        return _skip(f"template ref unchanged ({new}); skipping")
    failure: str | None = None
    changes: list[tuple[str, str]] = []
    if _reexec_with_deps():
        failure = "copier is not importable and `uv` is not available to fetch it"
    else:
        try:
            changes = _compute(src, old, new, current)
        except Exception as exc:  # any failure is reported in the file, never raised
            failure = f"{type(exc).__name__}: {exc}"
    REPORT.write_text(
        render_report(src=src, old=old, new=new, changes=changes, failure=failure),
        encoding="utf-8",
    )
    if failure:
        print(
            f"report_seeded_changes: WARNING could not compute the report ({failure}); wrote {REPORT}"
        )
    else:
        print(
            f"report_seeded_changes: {len(changes)} seeded file(s) changed {old} → {new}; wrote {REPORT}"
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
